apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-distr.fullname" . }}-jobs
  labels:
    {{- include "hello-distr.component.labels" (dict "component" "jobs" "context" .) | nindent 4 }}
spec:
  replicas: {{ .Values.jobs.replicaCount }}
  selector:
    matchLabels:
      {{- include "hello-distr.component.selectorLabels" (dict "component" "jobs" "context" .) | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/jobs-configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "hello-distr.component.labels" (dict "component" "jobs" "context" .) | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hello-distr.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: jobs
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.jobs.image.repository }}:{{ .Values.jobs.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.jobs.image.pullPolicy }}
          livenessProbe:
            exec:
              command:
                - pgrep
                - busybox
          {{- with .Values.jobs.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: crontab
              mountPath: /etc/crontabs/root
              subPath: root
              readOnly: true
      volumes:
        - name: crontab
          configMap:
            name: {{ include "hello-distr.fullname" . }}-jobs
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
