# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Hello Distr

on:
  pull_request:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  build:
    name: Build ${{ matrix.service }}
    timeout-minutes: 20
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        service: [backend, frontend, proxy, jobs]

    steps:
      - name: Login to GitHub Container Registry
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
      - name: Generate Docker Metadata
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        with:
          images: ghcr.io/distr-sh/hello-distr/${{ matrix.service }}
          tags: |
            type=ref,event=branch
            type=sha,event=branch
            type=semver,pattern={{version}}
          labels: |
            org.opencontainers.image.description=Hello Distr ${{ matrix.service }}
            org.opencontainers.image.vendor=Distr
      - name: Docker build (push only for tag)
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          platforms: ${{ startsWith(github.ref, 'refs/tags/') && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
          context: "{{defaultContext}}:${{ matrix.service }}"
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.service }}
          cache-to: type=gha,mode=max,scope=${{ matrix.service }}
          build-args: |
            VERSION=${{ github.ref_name }}

  build-chart:
    name: Build chart
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
      - name: Build helm chart
        run: |
          helm dependency build deploy/charts/hello-distr
          helm lint --strict deploy/charts/hello-distr
          helm package deploy/charts/hello-distr
      - name: Login to GitHub Container Registry
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push helm chart
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: helm push hello-distr-*.tgz oci://ghcr.io/distr-sh/charts

  distr-docker:
    name: Update Docker deployments
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    strategy:
      matrix:
        include:
          - DISTR_TOKEN_SECRET: DISTR_TOKEN
            DISTR_APPLICATION_ID_VAR: DISTR_APPLICATION_ID
          - DISTR_TOKEN_SECRET: DISTR_TOKEN_PMIG
            DISTR_APPLICATION_ID_VAR: DISTR_APPLICATION_ID_PMIG
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6

      - name: Create Distr Version
        id: distr-create-version
        uses: distr-sh/distr-create-version-action@v1.4.1
        with:
          api-token: ${{ secrets[matrix.DISTR_TOKEN_SECRET] }}
          api-base: "https://demo.distr.sh/api/v1"
          application-id: ${{ vars[matrix.DISTR_APPLICATION_ID_VAR] }}
          version-name: ${{ github.ref_name }}
          compose-file: ${{ github.workspace }}/deploy/docker-compose.yaml
          template-file: ${{ github.workspace }}/deploy/env.template
          link-template: "{{ .Env.HELLO_DISTR_PROTOCOL }}://{{ .Env.HELLO_DISTR_HOST }}"
          update-deployments: true

      - name: Print Application Version ID
        id: output
        run: echo "${{ steps.distr-create-version.outputs.created-version-id }}"
